### ISSUE TITLE
Incorporate default namespace into resource generator for BEL 2.0 support.

### ISSUE THREAD

**Issue by abargnesi** [OpenBEL/resource-generator#72]
@wshayes put together an [RDF SKOS resource file](https://github.com/OpenBEL/language/blob/master/rdf-schema/bel-default-namespace.ttl) for the default BEL namespace.

This should be incorporated into the resource-generator build to produce a BEL namespace file.

In the future it would be helpful to also equivalence our activities to GO's molecular function tree once we have it.

**Comment by nbargnesi** [comment]
Closing. The OpenBEL build server project [OpenBEL Resources](http://build.openbel.org/browse/OR) will be publishing the default namespace momentarily.
